name: Test on Multiple OS and Python Versions

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip list
      - name: Check Python version
        run: python --version
      - name: Check working directory
        run: |
          if (${{ runner.os }} -eq 'Windows') {
            echo $PWD
          } else {
            pwd
          }
        shell: pwsh
      - name: List directory contents
        run: |
          if (${{ runner.os }} -eq 'Windows') {
            dir
          } else {
            ls -al
          }
        shell: pwsh
      - name: Run tests
        run: |
          if (${{ runner.os }} -eq 'Windows') {
            python -m unittest discover
          } else {
            python -m unittest example_test_suite_v2.py
          }
        shell: pwsh
