name: Test on Multiple OS and Python Versions

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip list
      - name: Check Python version
        run: python --version
      - name: Check working directory
        run: |
          if [ "${{ runner.os }}" == 'Windows' ]; then
            echo %CD%
          else
            pwd
          endif
      - name: List directory contents
        run: |
          if [ "${{ runner.os }}" == 'Windows' ]; then
            dir
          else
            ls -al
          endif
      - name: Run tests
        run: python -m unittest discover
